-- Raw tables preserve source values before cleaning or type conversion.

CREATE TABLE IF NOT EXISTS raw.games (
    season_id TEXT,
    team_id_home TEXT,
    team_abbreviation_home TEXT,
    team_name_home TEXT,
    game_id TEXT,
    game_date TEXT,
    matchup_home TEXT,
    wl_home TEXT,
    min TEXT,
    fgm_home TEXT,
    fga_home TEXT,
    fg_pct_home TEXT,
    fg3m_home TEXT,
    fg3a_home TEXT,
    fg3_pct_home TEXT,
    ftm_home TEXT,
    fta_home TEXT,
    ft_pct_home TEXT,
    oreb_home TEXT,
    dreb_home TEXT,
    reb_home TEXT,
    ast_home TEXT,
    stl_home TEXT,
    blk_home TEXT,
    tov_home TEXT,
    pf_home TEXT,
    pts_home TEXT,
    plus_minus_home TEXT,
    video_available_home TEXT,
    team_id_away TEXT,
    team_abbreviation_away TEXT,
    team_name_away TEXT,
    matchup_away TEXT,
    wl_away TEXT,
    fgm_away TEXT,
    fga_away TEXT,
    fg_pct_away TEXT,
    fg3m_away TEXT,
    fg3a_away TEXT,
    fg3_pct_away TEXT,
    ftm_away TEXT,
    fta_away TEXT,
    ft_pct_away TEXT,
    oreb_away TEXT,
    dreb_away TEXT,
    reb_away TEXT,
    ast_away TEXT,
    stl_away TEXT,
    blk_away TEXT,
    tov_away TEXT,
    pf_away TEXT,
    pts_away TEXT,
    plus_minus_away TEXT,
    video_available_away TEXT,
    season_type TEXT,
    source_table TEXT NOT NULL DEFAULT 'game',
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.players (
    id TEXT,
    full_name TEXT,
    first_name TEXT,
    last_name TEXT,
    is_active TEXT,
    source_table TEXT NOT NULL DEFAULT 'player',
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.teams (
    id TEXT,
    full_name TEXT,
    abbreviation TEXT,
    nickname TEXT,
    city TEXT,
    state TEXT,
    year_founded TEXT,
    source_table TEXT NOT NULL DEFAULT 'team',
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.game_summary (
    game_date_est TEXT,
    game_sequence TEXT,
    game_id TEXT,
    game_status_id TEXT,
    game_status_text TEXT,
    gamecode TEXT,
    home_team_id TEXT,
    visitor_team_id TEXT,
    season TEXT,
    live_period TEXT,
    live_pc_time TEXT,
    natl_tv_broadcaster_abbreviation TEXT,
    live_period_time_bcast TEXT,
    wh_status TEXT,
    source_table TEXT NOT NULL DEFAULT 'game_summary',
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.line_scores (
    game_date_est TEXT,
    game_sequence TEXT,
    game_id TEXT,
    team_id_home TEXT,
    team_abbreviation_home TEXT,
    team_city_name_home TEXT,
    team_nickname_home TEXT,
    team_wins_losses_home TEXT,
    pts_qtr1_home TEXT,
    pts_qtr2_home TEXT,
    pts_qtr3_home TEXT,
    pts_qtr4_home TEXT,
    pts_ot1_home TEXT,
    pts_ot2_home TEXT,
    pts_ot3_home TEXT,
    pts_ot4_home TEXT,
    pts_ot5_home TEXT,
    pts_ot6_home TEXT,
    pts_ot7_home TEXT,
    pts_ot8_home TEXT,
    pts_ot9_home TEXT,
    pts_ot10_home TEXT,
    pts_home TEXT,
    team_id_away TEXT,
    team_abbreviation_away TEXT,
    team_city_name_away TEXT,
    team_nickname_away TEXT,
    team_wins_losses_away TEXT,
    pts_qtr1_away TEXT,
    pts_qtr2_away TEXT,
    pts_qtr3_away TEXT,
    pts_qtr4_away TEXT,
    pts_ot1_away TEXT,
    pts_ot2_away TEXT,
    pts_ot3_away TEXT,
    pts_ot4_away TEXT,
    pts_ot5_away TEXT,
    pts_ot6_away TEXT,
    pts_ot7_away TEXT,
    pts_ot8_away TEXT,
    pts_ot9_away TEXT,
    pts_ot10_away TEXT,
    pts_away TEXT,
    source_table TEXT NOT NULL DEFAULT 'line_score',
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_raw_games_game_id ON raw.games (game_id);
CREATE INDEX IF NOT EXISTS ix_raw_players_id ON raw.players (id);
CREATE INDEX IF NOT EXISTS ix_raw_teams_id ON raw.teams (id);
CREATE INDEX IF NOT EXISTS ix_raw_game_summary_game_id ON raw.game_summary (game_id);
CREATE INDEX IF NOT EXISTS ix_raw_line_scores_game_id ON raw.line_scores (game_id);